baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Raspberry pi hosted personal site'
theme = 'hello-friend-ng'

[markup.goldmark.renderer]
unsafe = true

[params]
  homeSubtitle = "Welcome to my small website! Use the header to navigate the site."
  description = "A minimal Hugo site using Hello Friend NG."


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Blog"
url = "/blog"
weight = 3

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 4

[[menu.main]]
name = "Contact"
url = "/contact"
weight = 5